export const link = "http://localhost:4000/api";

//Alert 

export const SET_ALERT = "SET_ALERT";
export const  REMOVE_ALERT = " REMOVE_ALERT";

// Auth

// Sign In

export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAIL = "SIGN_IN_FAIL";

//Sign Up

export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";

//Complete Registration

export const COMPLETE_REGISTRATION_REQUEST = "COMPLETE_REGISTRATION_REQUEST";
export const COMPLETE_REGISTRATION_SUCCESS = "COMPLETE_REGISTRATION_SUCCESS";
export const COMPLETE_REGISTRATION_FAIL = "COMPLETE_REGISTRATION_FAIL";

// Get user details

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";

//Post

export const NEW_POST_REQUEST = "NEW_POST_REQUEST";
export const NEW_POST_SUCCESS = "NEW_POST_SUCCESS";
export const NEW_POST_FAIL = "NEW_POST_FAIL";

export const EDIT_POST_REQUEST = "EDIT_POST_REQUEST";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const EDIT_POST_FAIL = "EDIT_POST_FAIL";

export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAIL = "UPDATE_POST_FAIL";

export const REMOVE_POST_REQUEST = "REMOVE_POST_REQUEST";
export const REMOVE_POST_SUCCESS = "REMOVE_POST_SUCCESS";
export const REMOVE_POST_FAIL = "REMOVE_POST_FAIL";

export const ALL_POST_REQUEST = "ALL_POST_REQUEST";
export const ALL_POST_SUCCESS = "ALL_POST_SUCCESS";
export const ALL_POST_FAIL = "ALL_POST_FAIL";

export const CATEGORY_POST_REQUEST = "CATEGORY_POST_REQUEST";
export const CATEGORY_POST_SUCCESS = "CATEGORY_POST_SUCCESS";
export const CATEGORY_POST_FAIL = "CATEGORY_POST_FAIL";

export const AUTHOR_POST_REQUEST = "AUTHOR_POST_REQUEST";
export const AUTHOR_POST_SUCCESS = "AUTHOR_POST_SUCCESS";
export const AUTHOR_POST_FAIL = "AUTHOR_POST_FAIL";